local_backend: true
backend:
  name: git-gateway
  branch: master
media_folder: content/site_images
collections:
  - label: "Language"
    name: "language"
    public_folder: content/language
    editor:
      preview: false
    files:
      - label: Dictionary
        name: dictionary
        file: content/language/dictionary.md
        fields:
          - label: Home
            name: dict_home
            widget: object
            fields:
              - label: English
                name: dict_home_en
              - label: Español
                name: dict_home_es
          - label: Read more
            name: dict_read_more
            widget: object
            fields:
              - label: English
                name: dict_read_more_en
              - label: Español
                name: dict_read_more_es
          - label: Profile
            name: dict_profile
            widget: object
            fields:
              - label: English
                name: dict_profile_en
              - label: Español
                name: dict_profile_es
          - label: Age
            name: dict_age
            widget: object
            fields:
              - label: English
                name: dict_age_en
              - label: Español
                name: dict_age_es
          - label: Sex
            name: dict_sex
            widget: object
            fields:
              - label: English
                name: dict_sex_en
              - label: Español
                name: dict_sex_es
          - label: Male
            name: dict_male
            widget: object
            fields:
              - label: English
                name: dict_male_en
              - label: Español
                name: dict_male_es
          - label: Female
            name: dict_female
            widget: object
            fields:
              - label: English
                name: dict_female_en
              - label: Español
                name: dict_female_es
          - label: Breed
            name: dict_breed
            widget: object
            fields:
              - label: English
                name: dict_breed_en
              - label: Español
                name: dict_breed_es
          - label: PPP?
            name: dict_ppp
            widget: object
            fields:
              - label: English
                name: dict_ppp_en
              - label: Español
                name: dict_ppp_es
          - label: Came into the shelter
            name: dict_came_in
            widget: object
            fields:
              - label: English
                name: dict_came_in_en
              - label: Español
                name: dict_came_in_es
          - label: Sociability
            name: dict_sociability
            widget: object
            fields:
              - label: English
                name: dict_sociability_en
              - label: Español
                name: dict_sociability_es
          - label: Children
            name: dict_children
            widget: object
            fields:
              - label: English
                name: dict_children_en
              - label: Español
                name: dict_children_es
          - label: Dogs
            name: dict_dogs
            widget: object
            fields:
              - label: English
                name: dict_dogs_en
              - label: Español
                name: dict_dogs_es
          - label: Cats
            name: dict_cats
            widget: object
            fields:
              - label: English
                name: dict_cats_en
              - label: Español
                name: dict_cats_es
          - label: View photos
            name: dict_view_photos
            widget: object
            fields:
              - label: English
                name: dict_view_photos_en
              - label: Español
                name: dict_view_photos_es
          - label: Share
            name: dict_share
            widget: object
            fields:
              - label: English
                name: dict_share_en
              - label: Español
                name: dict_share_es
          - label: Description
            name: dict_description
            widget: object
            fields:
              - label: English
                name: dict_description_en
              - label: Español
                name: dict_description_es
          - label: Common queries
            name: dict_common_queries
            widget: object
            fields:
              - label: English
                name: dict_common_queries_en
              - label: Español
                name: dict_common_queries_es
          - label: Name
            name: dict_name
            widget: object
            fields:
              - label: English
                name: dict_name_en
              - label: Español
                name: dict_name_es
          - label: Email
            name: dict_email
            widget: object
            fields:
              - label: English
                name: dict_email_en
              - label: Español
                name: dict_email_es
          - label: Phone
            name: dict_phone
            widget: object
            fields:
              - label: English
                name: dict_phone_en
              - label: Español
                name: dict_phone_es
          - label: Message
            name: dict_message
            widget: object
            fields:
              - label: English
                name: dict_message_en
              - label: Español
                name: dict_message_es
          - label: Send
            name: dict_send
            widget: object
            fields:
              - label: English
                name: dict_send_en
              - label: Español
                name: dict_send_es
      - label: "Change language prompt"
        name: "language_prompt"
        file: "content/language/prompt.md"
        fields:
          - label: Redirect prompt
            name: redirect_prompt
            widget: object
            fields:
              - label: English
                hint: The message displayed to the user asking if they want to change to English
                name: redirect_prompt_en
              - label: Español
                hint: The message displayed to the user asking if they want to change to Spanish
                name: redirect_prompt_es
          - label: Opt out
            name: opt_out
            hint: The message displayed next to the checkbox re not showing the prompt in future
            widget: object
            fields:
              - label: English
                name: opt_out_en
              - label: Español
                name: opt_out_es
  - name: "articles_en"
    label: "Articles (English)"
    label_singular: "Article (English)"
    folder: "content/articles/english"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    summary: "{{day}}/{{month}}/{{year}} - {{title}}"
    fields:
      - label: "Make public?"
        name: "publish"
        widget: "boolean"
        default: true
      - label: "Title"
        name: "title"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        choose_url: false
      - label: "Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic"]
        editor_components: ["image"]
        modes: ["rich_text"]
  - name: "articles_es"
    label: "Articles (Español)"
    label_singular: "Article (Español)"
    folder: "content/articles/espanol"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    summary: "{{day}}/{{month}}/{{year}} - {{title}}"
    fields:
      - label: "Make public?"
        name: "publish"
        widget: "boolean"
        default: true
      - label: "Title"
        name: "title"
      - label: "Featured Image"
        name: "featured_image"
        widget: "image"
        choose_url: false
      - label: "Date"
        name: "date"
        widget: "datetime"
        time_format: false
        date_format: "DD/MM/YYYY"
      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: ["bold", "italic"]
        editor_components: ["image"]
        modes: ["rich_text"]
  - name: "dogs"
    label: "Dogs"
    label_singular: "Dog"
    folder: "content/dogs"
    create: true
    editor:
      preview: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{slug}}/index"
    media_folder: ""
    summary: "{{dog_name}} ({{dog_breed}})"
    fields:
      - label: "Name"
        name: "dog_name"
      - label: "Sex"
        name: "dog_sex"
        widget: "select"
        options:
          - { label: "Male", value: "0" }
          - { label: "Female", value: "1" }
      - label: "Breed"
        name: "dog_breed"
        widget: object
        fields:
          - name: "dog_breed_en"
            label: English
          - name: "dog_breed_es"
            label: "Español"
      - label: "Date of birth"
        name: "dog_date_of_birth"
        widget: "datetime"
        time_format: false
        date_format: "DD/MM/YYYY"
      - label: "Date entered"
        name: "dog_date_entered"
        widget: "datetime"
        time_format: false
        date_format: "DD/MM/YYYY"
      - label: "Images"
        name: "dog_images"
        widget: "list"
        field:
          {
            label: "Image",
            name: "dog_image",
            widget: "image",
            choose_url: false,
          }
        hint: "Note: The first image will be the main profile pic"
        required: false
      - label: "PPP?"
        name: "dog_ppp"
        widget: "select"
        options:
          - { label: "No", value: "0" }
          - { label: "Yes", value: "1" }
          - { label: "TBC", value: "2" }
      - label: "Sociability"
        name: "dog_sociability"
        widget: "object"
        fields:
          - label: "Children"
            name: "dog_sociability_children"
            widget: "select"
            options:
              - { label: "No", value: "0" }
              - { label: "Yes", value: "1" }
              - { label: "TBC", value: "2" }
          - label: "Dogs"
            name: "dog_sociability_dogs"
            widget: "select"
            options:
              - { label: "No", value: "0" }
              - { label: "Yes", value: "1" }
              - { label: "TBC", value: "2" }
          - label: "Cats"
            name: "dog_sociability_cats"
            widget: "select"
            options:
              - { label: "No", value: "0" }
              - { label: "Yes", value: "1" }
              - { label: "TBC", value: "2" }
      - label: "Description"
        name: "dog_description"
        widget: "object"
        fields:
          - {
              label: "English",
              name: "dog_description_en",
              widget: markdown,
              buttons: ["bold", "italic", "link"],
              editorComponents: [],
            }
          - {
              label: "Español",
              name: "dog_description_es",
              widget: markdown,
              buttons: ["bold", "italic", "link"],
              editorComponents: [],
            }
  - label: "Pages"
    name: "pages"
    media_folder: "./site_images"
    public_folder: "site_images"
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/static_pages/homepage.md"
        fields:
          - label: "Main image (Landscape)"
            name: "homepage_main_image_landscape"
            widget: "image"
            hint: "A landscape image to be displayed on laptop/desktop computer screens"
          - label: "Main image (Portrait)"
            name: "homepage_main_image_portrait"
            widget: "image"
            hint: "A portrait image to be displayed on mobile screens"
          - label: "Heading"
            name: "homepage_heading"
            widget: "object"
            fields:
              - label: "Español"
                name: "homepage_heading_es"
              - label: "English"
                name: "homepage_heading_en"
          - label: "Subheading"
            name: "homepage_subheading"
            widget: "object"
            fields:
              - label: "Español"
                name: "homepage_subheading_es"
              - label: "English"
                name: "homepage_subheading_en"
          - label: "Call to Action #1"
            name: "homepage_cta_1"
            hint: "The first button on the homepage"
            widget: "object"
            fields:
              - label: "Page"
                name: "homepage_cta_1_page"
                widget: "select"
                options:
                  - { label: "The about page", value: "about" }
                  - { label: "The adopt page", value: "adopt" }
                  - { label: "The foster page", value: "foster" }
                  - { label: "The news page", value: "news" }
                  - { label: "The donate page", value: "donate" }
                  - { label: "The volunteer page", value: "volunteer" }
                  - { label: "The dogs page", value: "the-dogs" }
                  - { label: "The contact page", value: "contact" }
              - label: "Button text"
                name: "homepage_cta_1_button_text"
                widget: "object"
                fields:
                  - label: "English"
                    name: "homepage_cta_1_button_text_en"
                  - label: "Español"
                    name: "homepage_cta_1_button_text_es"
          - label: "Call to Action #2"
            name: "homepage_cta_2"
            hint: "The second button on the homepage"
            widget: "object"
            fields:
              - label: "Page"
                name: "homepage_cta_2_page"
                widget: "select"
                options:
                  - { label: "The about page", value: "about" }
                  - { label: "The adopt page", value: "adopt" }
                  - { label: "The foster page", value: "foster" }
                  - { label: "The donate page", value: "donate" }
                  - { label: "The news page", value: "news" }
                  - { label: "The volunteer page", value: "volunteer" }
                  - { label: "The dogs page", value: "the-dogs" }
                  - { label: "The contact page", value: "contact" }
              - label: "Button text"
                name: "homepage_cta_2_button_text"
                widget: "object"
                fields:
                  - label: "English"
                    name: "homepage_cta_2_button_text_en"
                  - label: "Español"
                    name: "homepage_cta_2_button_text_es"
      - label: Contact us
        name: contact_us
        file: "content/static_pages/contact_us.md"
        fields:
          - label: Common queries alert
            name: contact_us_common_queries_alert
            widget: object
            fields:
              - label: English
                name: contact_us_common_queries_alert_en
              - label: Español
                name: contact_us_common_queries_alert_es
          - label: Common queries
            name: contact_us_common_queries
            widget: object
            fields:
              - label: English
                name: contact_us_common_queries_en
                widget: list
                label_singular: query
                summary: "{{fields.query}}"
                fields:
                  - label: Query
                    name: query
                  - label: Response
                    name: response
                    widget: text
              - label: Español
                name: contact_us_common_queries_es
                widget: list
                label_singular: query
                summary: "{{fields.query}}"
                fields:
                  - label: Query
                    name: query
                  - label: Response
                    name: response
                    widget: text
          - label: Buttons intro text
            name: contact_us_buttons_intro_text
            widget: object
            fields:
              - label: English
                name: contact_us_buttons_intro_text_en
                widget: text
              - label: Español
                name: contact_us_buttons_intro_text_es
                widget: text
          - label: Contact form intro text
            name: contact_us_contact_form_intro_text
            widget: object
            fields:
              - label: English
                name: contact_us_contact_form_intro_text_en
                widget: text
              - label: Español
                name: contact_us_contact_form_intro_text_es
                widget: text
          - label: Contact form message sent
            name: contact_us_contact_form_message_sent
            widget: object
            fields:
              - label: English
                name: contact_us_contact_form_message_sent_en
              - label: Español
                name: contact_us_contact_form_message_sent_es
          - label: Contact form message failed
            name: contact_us_contact_form_message_failed
            widget: object
            fields:
              - label: English
                name: contact_us_contact_form_message_failed_en
              - label: Español
                name: contact_us_contact_form_message_failed_es
